// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEsc02_32Md3QtPQsRhLUvEq48o3xA1wo',
    appId: '1:164991754779:web:e03fd4da14b2d274c34ebe',
    messagingSenderId: '164991754779',
    projectId: 'coworkbd-6e5de',
    authDomain: 'coworkbd-6e5de.firebaseapp.com',
    storageBucket: 'coworkbd-6e5de.firebasestorage.app',
    measurementId: 'G-0S8GVRY2D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxlLnsl0HAs9jX90QSvbrJ898FrHhPWzo',
    appId: '1:164991754779:android:b32133c9071ac241c34ebe',
    messagingSenderId: '164991754779',
    projectId: 'coworkbd-6e5de',
    storageBucket: 'coworkbd-6e5de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1E0TI_wlZLnocB05UqL_30e0xr-VZhZk',
    appId: '1:164991754779:ios:153e6ef8d99e6640c34ebe',
    messagingSenderId: '164991754779',
    projectId: 'coworkbd-6e5de',
    storageBucket: 'coworkbd-6e5de.firebasestorage.app',
    androidClientId: '164991754779-p7qb5ju55ibet4p9ipm1an8d2l0824fm.apps.googleusercontent.com',
    iosClientId: '164991754779-jfqnq6egph37pgphhddtv8684qmj0t2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.coworkFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1E0TI_wlZLnocB05UqL_30e0xr-VZhZk',
    appId: '1:164991754779:ios:153e6ef8d99e6640c34ebe',
    messagingSenderId: '164991754779',
    projectId: 'coworkbd-6e5de',
    storageBucket: 'coworkbd-6e5de.firebasestorage.app',
    androidClientId: '164991754779-p7qb5ju55ibet4p9ipm1an8d2l0824fm.apps.googleusercontent.com',
    iosClientId: '164991754779-jfqnq6egph37pgphhddtv8684qmj0t2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.coworkFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEsc02_32Md3QtPQsRhLUvEq48o3xA1wo',
    appId: '1:164991754779:web:b4fad78fbaed4151c34ebe',
    messagingSenderId: '164991754779',
    projectId: 'coworkbd-6e5de',
    authDomain: 'coworkbd-6e5de.firebaseapp.com',
    storageBucket: 'coworkbd-6e5de.firebasestorage.app',
    measurementId: 'G-9DNZCT9T19',
  );

}